version: "3.8"
services:
  notebook:
    build:
      context: .
      dockerfile: ./notebook.dockerfile
      target: notebook
    expose:
      - "8888"
    image: notebook
    ports:
      - "8888:8888"
    volumes:
      - ~/.ssh:/home/jovyan/.ssh
      - ~/code/py/ipynb:/home/jovyan/work:rw
      - ~/Downloads:/Downloads:rw
      - ~/Documents:/Documents:rw
      - ~/git:/git:rw